### ISSUE TITLE
Feature request: if possible, support variable column definitions?

### ISSUE THREAD

**Issue by simonw** [coleifer/sqlite-vtfunc#8]
Would it be possible to allow virtual table functions to dynamically decide the columns that they are planning to return based on their input?

I'm assuming this is impossible (if so, please close this issue) - based on my very loose understanding of how SQLite virtual tables work and this bit of code here:

https://github.com/coleifer/sqlite-vtfunc/blob/411c411a6d9f6466a4eef492de68dbd8c41a8dfc/vtfunc.pyx#L210-L213

The reason I want this is that I'd like to build a `fetch_json_array(url)` function which can fetch data from a JSON API that returns data something like like this:

```
[
  {"id": 4, "name": "Bob", "age": 34},
  {"id": 6, "name": "Karen", "age": 37}
]
```
Ideally I'd be able to do the following:
```
select * from fetch_json_array("http://example.com/users.json")
```
And get back a table like this:

| id | name | age |
|----|------|-----|
| 4  | Bob  | 34  |
| 6  | Karen  | 37  |

That's one column for each of the properties in the returned JSON.

But... vtfunc definitions are required to hard-code the list of `columns` - so this isn't currently possible.

If this DOES turn out to be impossible then I'll probably work around this using features from SQLite's `json1` module, but it would be fantastic if there was a way to dynamically calculate columns in this way.

**Comment by coleifer** [comment]
I don't believe this is do-able. Read the [SQLite virtual tables](https://www.sqlite.org/vtab.html) API doc for background. What vtfunc does is it takes your `TableFunction` and tells sqlite (via `sqlite3_create_module`) that the table function provides a virtual table and implements x, y, z methods. vtfunc makes an additional caveat in the way it declares its callbacks that it is an eponymous-only virtual table (e.g., you cannot create virtual table ... with the tablefunction module). When sqlite sees us querying our virtual table directly, it calls the xConnect callback we registered. At this point we have no information about the query, the parameters, the row values...nothing...*and* we need to tell sqlite the structure of our table (`sqlite3_declare_vtab`). If you look in the code for `pwConnect` you'll see that there's no `TableFunction` instance in there -- because we don't have enough information yet to create one. That happens later in the `xOpen` callback.
